const fs = require('fs');
const path = require('path');
const { extractEvents } = require('../ai');
const { fetchYutoriEmails } = require('../gmail');
const { normalizeExtractedEvent } = require('./shared');
const { captureExtractionInput } = require('../extraction-capture');

const YUTORI_DIR = path.join(__dirname, '../../data/yutori');
const PROCESSED_DIR = path.join(YUTORI_DIR, 'processed');
const PROCESSED_IDS_FILE = path.join(YUTORI_DIR, 'processed-ids.json');
const CACHE_FILE = path.join(YUTORI_DIR, 'cached-events.json');

/**
 * Non-event scout categories — skip these before extraction.
 */
const NON_EVENT_CATEGORIES = [
  /fintech/i, /banking/i, /finance/i, /investment/i, /portfolio/i, /market/i,
  /sports?\s+(betting|ticket|fan)/i, /fantasy\s+sports/i,
  /crypto/i, /blockchain/i, /defi/i,
  /real\s+estate/i, /mortgage/i,
  /insurance/i, /health\s*care/i,
];

/**
 * Non-event filename patterns — catch fintech/sports emails by subject slug.
 */
const NON_EVENT_FILENAMES = [
  /fintech/i, /agentic-ai/i, /banking/i, /jpmorgan/i, /stripe/i, /vestwell/i,
  /apple-s-bonus/i, /de-risking/i, /price-drop/i, /occ-nod/i,
  /cpb-screen/i, /index-trigger/i, /value-setup/i,
  /knicks/i, /nets/i, /yankees/i, /mets/i,
];

/**
 * Check if a Yutori email contains events worth extracting.
 * Returns false for fintech, sports, and other non-event scout categories.
 */
function isEventEmail(filename, html) {
  // Check filename patterns first (cheap)
  for (const pat of NON_EVENT_FILENAMES) {
    if (pat.test(filename)) {
      return false;
    }
  }

  // Extract the scout category label from the uppercase <p> near the top
  const categoryMatch = html.match(
    /text-transform:\s*uppercase[^>]*>\s*<a[^>]*style="[^"]*text-decoration-line:\s*none"[^>]*>([^<]+)<\/a>/i
  );
  if (categoryMatch) {
    const category = categoryMatch[1].trim();
    for (const pat of NON_EVENT_CATEGORIES) {
      if (pat.test(category)) {
        return false;
      }
    }
  }

  return true;
}

/**
 * Preprocess Yutori HTML into clean text optimized for event extraction.
 * Strips email chrome, unwraps tracking URLs, removes boilerplate.
 * Falls back to generic stripHtml if preprocessing produces empty output.
 */
function preprocessYutoriHtml(html) {
  let text = html;

  // Strip everything before first <h3> (email header chrome)
  const h3Index = text.indexOf('<h3');
  if (h3Index > 0) {
    text = text.slice(h3Index);
  }

  // Strip everything after "Report generated by" (footer boilerplate)
  const reportIdx = text.indexOf('Report generated by');
  if (reportIdx > 0) {
    text = text.slice(0, reportIdx);
  }

  // Unwrap Yutori tracking URLs: scouts.yutori.com/api/view?url=ENCODED → inner URL
  text = text.replace(
    /https?:\/\/scouts\.yutori\.com\/api\/view\?url=([^&"'\s]+)[^"'\s]*/gi,
    (_, encoded) => {
      try {
        return decodeURIComponent(encoded);
      } catch {
        return encoded;
      }
    }
  );

  // Convert source link badges to [Source: url] markers
  text = text.replace(
    /<a\s[^>]*href=["']([^"']*(?:ra\.co|eventbrite|instagram|dice\.fm|songkick|brooklynvegan|ohmyrockness|prs\.org|thecitylife)[^"']*)["'][^>]*>.*?<\/a>/gi,
    (_, url) => `[Source: ${url}]`
  );

  // Convert remaining <a href="url">text</a> to "text (url)"
  text = text.replace(/<a\s[^>]*href=["']([^"']*)["'][^>]*>(.*?)<\/a>/gi, (_, url, linkText) => {
    const clean = linkText.replace(/<[^>]*>/g, '').trim();
    if (!clean || clean === url) return url;
    return `${clean} (${url})`;
  });

  // Convert <li> items to [Event] blocks
  text = text.replace(/<li[^>]*>([\s\S]*?)<\/li>/gi, (_, content) => {
    const clean = content
      .replace(/<b[^>]*>(.*?)<\/b>/gi, '$1')
      .replace(/<strong[^>]*>(.*?)<\/strong>/gi, '$1')
      .replace(/<em[^>]*>(.*?)<\/em>/gi, '$1')
      .replace(/<i[^>]*>(.*?)<\/i>/gi, '$1')
      .replace(/<span[^>]*>[\s\S]*?<\/span>/gi, '')
      .replace(/<img[^>]*>/gi, '')
      .replace(/<[^>]*>/g, '')
      .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&#x27;/g, "'")
      .replace(/&nbsp;/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
    if (clean.length < 20) return '';
    return `\n[Event] ${clean}\n`;
  });

  // Convert <h3>, <p>, <strong>/<b> section headers to plain text
  text = text.replace(/<h3[^>]*>(.*?)<\/h3>/gi, '\n## $1\n');
  text = text.replace(/<p[^>]*>(.*?)<\/p>/gi, '\n$1\n');
  text = text.replace(/<b[^>]*>(.*?)<\/b>/gi, '$1');
  text = text.replace(/<strong[^>]*>(.*?)<\/strong>/gi, '$1');

  // Strip remaining HTML tags
  text = text.replace(/<[^>]*>/g, '');

  // Decode entities
  text = text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>');
  text = text.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&#x27;/g, "'");
  text = text.replace(/&nbsp;/g, ' ');

  // Strip boilerplate phrases
  text = text.replace(/\[object Object\]/g, '');
  text = text.replace(/Anything I should adjust\?.*$/gm, '');
  text = text.replace(/Know someone who.*$/gm, '');
  text = text.replace(/Manage Scout/g, '');
  text = text.replace(/Invite them to subscribe/g, '');

  // Collapse whitespace
  text = text.replace(/[ \t]+/g, ' ').replace(/\n{3,}/g, '\n\n').trim();

  // Fall back to generic stripHtml if preprocessing produced empty/tiny output
  if (text.length < 50) {
    return stripHtml(html);
  }
  return text;
}

/**
 * Strip HTML to plain text, preserving <a href> URLs as "text (URL)" format.
 */
function stripHtml(html) {
  return html
    // Convert <a href="url">text</a> to "text (url)"
    .replace(/<a\s[^>]*href=["']([^"']*)["'][^>]*>(.*?)<\/a>/gi, (_, url, text) => {
      const cleanText = text.replace(/<[^>]*>/g, '').trim();
      // If the link text is the URL itself, just keep the URL
      if (cleanText === url || !cleanText) return url;
      return `${cleanText} (${url})`;
    })
    // Convert <br> and block elements to newlines
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/(p|div|h[1-6]|li|tr)>/gi, '\n')
    // Strip remaining tags
    .replace(/<[^>]*>/g, '')
    // Decode common HTML entities
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    // Collapse whitespace but preserve paragraph breaks
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/**
 * Load cached events from previously processed briefings.
 */
function loadCachedEvents() {
  try {
    if (fs.existsSync(CACHE_FILE)) {
      return JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8'));
    }
  } catch (err) {
    console.warn('Yutori: failed to load cached-events.json:', err.message);
  }
  return null;
}

/**
 * Save extracted events, accumulating with previously cached events.
 * Dedupes by event ID and prunes events >30 days in the past.
 */
function saveCachedEvents(newEvents) {
  try {
    fs.mkdirSync(YUTORI_DIR, { recursive: true });

    // Load existing cached events and merge
    const existing = loadCachedEvents();
    const existingEvents = existing?.events || [];
    const seen = new Set(newEvents.map(e => e.id));
    const kept = existingEvents.filter(e => !seen.has(e.id));
    const merged = [...newEvents, ...kept];

    // Prune events with dates >30 days in the past
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - 30);
    const cutoffStr = cutoff.toISOString().slice(0, 10);
    const pruned = merged.filter(e => {
      const d = e.date_local;
      if (!d) return true; // keep undated events
      return d >= cutoffStr;
    });

    fs.writeFileSync(CACHE_FILE, JSON.stringify({ events: pruned, timestamp: Date.now() }, null, 2));
  } catch (err) {
    console.warn('Yutori: failed to save cached-events.json:', err.message);
  }
}

/**
 * Load the set of already-processed Gmail message IDs.
 */
function loadProcessedIds() {
  try {
    if (fs.existsSync(PROCESSED_IDS_FILE)) {
      return new Set(JSON.parse(fs.readFileSync(PROCESSED_IDS_FILE, 'utf8')));
    }
  } catch (err) {
    console.warn('Yutori: failed to load processed-ids.json:', err.message);
  }
  return new Set();
}

/**
 * Save the set of processed Gmail message IDs.
 */
function saveProcessedIds(ids) {
  try {
    fs.mkdirSync(YUTORI_DIR, { recursive: true });
    fs.writeFileSync(PROCESSED_IDS_FILE, JSON.stringify([...ids], null, 2));
  } catch (err) {
    console.warn('Yutori: failed to save processed-ids.json:', err.message);
  }
}

/**
 * Create a filename slug from a subject and date string.
 */
function makeFilename(subject, dateStr) {
  const date = dateStr ? new Date(dateStr) : new Date();
  const ymd = isNaN(date.getTime()) ? new Date().toISOString().slice(0, 10) : date.toISOString().slice(0, 10);
  const slug = (subject || 'briefing')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);
  return `${ymd}-${slug}.html`;
}

/**
 * Fetch Yutori emails from Gmail and save new ones to data/yutori/ as .html files.
 * Returns the number of new emails saved.
 */
async function ingestFromGmail() {
  const emails = await fetchYutoriEmails(48);
  if (emails.length === 0) {
    return 0;
  }

  const processedIds = loadProcessedIds();
  fs.mkdirSync(YUTORI_DIR, { recursive: true });

  let saved = 0;
  for (const email of emails) {
    if (processedIds.has(email.id)) {
      continue;
    }

    const filename = makeFilename(email.subject, email.date);
    const filepath = path.join(YUTORI_DIR, filename);

    // Skip if a file with this name already exists (from manual placement or prior run)
    if (fs.existsSync(filepath)) {
      processedIds.add(email.id);
      continue;
    }

    try {
      fs.writeFileSync(filepath, email.body, 'utf8');
      processedIds.add(email.id);
      saved++;
      console.log(`Yutori: saved Gmail email → ${filename}`);
    } catch (err) {
      console.warn(`Yutori: failed to save ${filename}:`, err.message);
    }
  }

  saveProcessedIds(processedIds);
  return saved;
}

/**
 * Scan extracted events for recurrence markers and upsert into recurring_patterns table.
 */
function processRecurrencePatterns(events) {
  const recurring = events.filter(e => e._raw?.is_recurring && e._raw?.recurrence_day);
  if (recurring.length === 0) return;

  try {
    const { upsertPattern } = require('../db');
    let count = 0;
    for (const e of recurring) {
      upsertPattern({
        name: e.name,
        venue_name: e.venue_name || 'TBA',
        venue_address: e.venue_address || null,
        neighborhood: e.neighborhood || null,
        day_of_week: e._raw.recurrence_day,
        time_local: e._raw.recurrence_time || null,
        end_time_local: null,
        category: e.category || null,
        subcategory: e.subcategory || null,
        is_free: e.is_free || false,
        price_display: e.price_display || null,
        description_short: e.description_short || null,
        source_name: 'yutori',
        source_url: e.source_url || null,
        ticket_url: e.ticket_url || null,
        extraction_confidence: e.extraction_confidence ?? null,
        last_confirmed: new Date().toISOString().slice(0, 10),
      });
      count++;
    }
    if (count > 0) {
      console.log(`Yutori: ${count} recurring patterns upserted`);
    }
  } catch (err) {
    // SQLite not available — skip pattern detection
    if (err.code !== 'MODULE_NOT_FOUND') {
      console.warn('Yutori: failed to upsert recurring patterns:', err.message);
    }
  }
}

async function fetchYutoriEvents() {
  console.log('Fetching Yutori agent briefings...');
  try {
    // Step 1: Try fetching from Gmail (no-op if credentials not configured)
    const gmailCount = await ingestFromGmail();
    if (gmailCount > 0) {
      console.log(`Yutori: ${gmailCount} new email(s) from Gmail`);
    }

    // Step 2: Process files in data/yutori/ (from Gmail or manual placement)
    if (!fs.existsSync(YUTORI_DIR)) {
      console.log('Yutori: data/yutori/ directory not found, skipping');
      return [];
    }

    const files = fs.readdirSync(YUTORI_DIR)
      .filter(f => /\.(txt|html?)$/i.test(f))
      .sort();

    if (files.length === 0) {
      // No new files — return cached events from last extraction
      const cached = loadCachedEvents();
      if (cached?.events?.length > 0) {
        console.log(`Yutori: returning ${cached.events.length} cached events (no new files)`);
        return cached.events;
      }

      // No cache exists — bootstrap by re-processing most recent file from processed/
      if (fs.existsSync(PROCESSED_DIR)) {
        const processed = fs.readdirSync(PROCESSED_DIR)
          .filter(f => /\.(txt|html?)$/i.test(f))
          .sort();
        if (processed.length > 0) {
          const latest = processed[processed.length - 1];
          console.log(`Yutori: bootstrapping cache from processed/${latest}`);
          // Move latest back to main dir for processing
          fs.renameSync(path.join(PROCESSED_DIR, latest), path.join(YUTORI_DIR, latest));
          // Re-run — will find the file, process it, cache, and move back
          return fetchYutoriEvents();
        }
      }

      console.log('Yutori: no briefing files found and no cache');
      return [];
    }

    // Process each file individually to stay within extraction limits
    const fileContents = [];
    for (const file of files) {
      const raw = fs.readFileSync(path.join(YUTORI_DIR, file), 'utf8');

      // Skip non-event emails (fintech, sports, etc.)
      if (/\.html?$/i.test(file) && !isEventEmail(file, raw)) {
        console.log(`Yutori: skipping non-event email → ${file}`);
        continue;
      }

      const content = /\.html?$/i.test(file) ? preprocessYutoriHtml(raw) : raw;
      if (content.length >= 50) {
        fileContents.push({ file, content });
      }
    }

    if (fileContents.length === 0) {
      console.log('Yutori: all briefing files too short, skipping');
      return [];
    }

    console.log(`Yutori: processing ${fileContents.length} files individually`);
    const events = [];

    // Process files in parallel (max 3 concurrent to avoid rate limits)
    const CONCURRENCY = 3;
    for (let i = 0; i < fileContents.length; i += CONCURRENCY) {
      const batch = fileContents.slice(i, i + CONCURRENCY);
      const results = await Promise.allSettled(
        batch.map(async ({ file, content }) => {
          console.log(`Yutori: extracting ${file} (${content.length} chars)`);
          const preamble = `[YUTORI CONTEXT]\nThis is a curated Yutori agent briefing about NYC events.\nEach event typically has: name, description, date/time, venue, address, price, source URL.\nExtract ALL events — including listening sessions, art openings, comedy, trivia, and small one-offs.\n\nRECURRENCE DETECTION:\nMany Yutori events are recurring weekly. Look for:\n- "every [day]", "weekly", "[day]s at [time]"\n- "Next: [date]" with a day-of-week pattern\n- Trivia nights, open mics, DJ residencies are often recurring\nSet is_recurring=true, recurrence_day, and recurrence_time when detected.\n[END CONTEXT]\n\n`;
          const enrichedContent = preamble + content;
          captureExtractionInput('yutori', enrichedContent, null);
          const result = await extractEvents(enrichedContent, 'yutori', null);
          return (result.events || [])
            .map(e => normalizeExtractedEvent(e, 'yutori', 'aggregator', 0.8))
            .filter(e => e.name && e.completeness >= 0.35);
        })
      );
      for (const r of results) {
        if (r.status === 'fulfilled') {
          events.push(...r.value);
        } else {
          console.warn('Yutori: extraction failed for batch item:', r.reason?.message);
        }
      }
    }

    // Move processed files to processed/ directory
    fs.mkdirSync(PROCESSED_DIR, { recursive: true });
    for (const file of files) {
      const src = path.join(YUTORI_DIR, file);
      const dest = path.join(PROCESSED_DIR, file);
      try {
        fs.renameSync(src, dest);
      } catch (err) {
        console.warn(`Yutori: failed to move ${file}: ${err.message}`);
      }
    }

    // Detect recurring patterns and upsert to SQLite
    processRecurrencePatterns(events);

    saveCachedEvents(events);
    console.log(`Yutori: ${events.length} events from ${files.length} briefings`);
    return events;
  } catch (err) {
    console.error('Yutori error:', err.message);
    return [];
  }
}

module.exports = { fetchYutoriEvents, stripHtml, preprocessYutoriHtml, isEventEmail };
