const fs = require('fs');
const path = require('path');
const { extractEvents } = require('../ai');
const { fetchYutoriEmails } = require('../gmail');
const { normalizeExtractedEvent, backfillEvidence } = require('./shared');
const { captureExtractionInput } = require('../extraction-capture');

const YUTORI_DIR = path.join(__dirname, '../../data/yutori');
const PROCESSED_DIR = path.join(YUTORI_DIR, 'processed');
const PROCESSED_IDS_FILE = path.join(YUTORI_DIR, 'processed-ids.json');
const CACHE_FILE = path.join(YUTORI_DIR, 'cached-events.json');

/**
 * Non-event scout categories — skip these before extraction.
 */
const NON_EVENT_CATEGORIES = [
  /fintech/i, /banking/i, /finance/i, /investment/i, /portfolio/i, /market/i,
  /sports?\s+(betting|ticket|fan)/i, /fantasy\s+sports/i,
  /crypto/i, /blockchain/i, /defi/i,
  /real\s+estate/i, /mortgage/i,
  /insurance/i, /health\s*care/i,
  // personal development / advice / lifestyle
  /personal\s+dev/i, /self[- ]?help/i, /coaching/i, /leadership/i,
  /psychology/i, /relationship/i, /social\s+skills/i, /friendships?/i,
  /productivity/i, /career/i, /hiring/i, /recruiting/i,
  /legal/i, /compliance/i, /tax\b/i,
];

/**
 * Non-event filename patterns — catch fintech/sports emails by subject slug.
 */
const NON_EVENT_FILENAMES = [
  /fintech/i, /agentic-ai/i, /banking/i, /jpmorgan/i, /stripe/i, /vestwell/i,
  /apple-s-bonus/i, /de-risking/i, /price-drop/i, /occ-nod/i,
  /cpb-screen/i, /index-trigger/i, /value-setup/i,
  /knicks/i, /nets/i, /yankees/i, /mets/i,
  // personal development / advice
  /friendship/i, /relationship/i, /self-help/i, /coaching/i,
  /leadership/i, /career-/i, /hiring-/i, /tax-/i, /legal-/i,
  /productivity/i, /psychology/i, /social-skill/i,
];

/**
 * Check if a Yutori email contains events worth extracting.
 * Returns false for fintech, sports, and other non-event scout categories.
 */
function isEventEmail(filename, html) {
  // Check filename patterns first (cheap)
  for (const pat of NON_EVENT_FILENAMES) {
    if (pat.test(filename)) {
      return false;
    }
  }

  // Extract the scout category label from the uppercase <p> near the top
  const categoryMatch = html.match(
    /text-transform:\s*uppercase[^>]*>\s*<a[^>]*style="[^"]*text-decoration-line:\s*none"[^>]*>([^<]+)<\/a>/i
  );
  if (categoryMatch) {
    const category = categoryMatch[1].trim();
    for (const pat of NON_EVENT_CATEGORIES) {
      if (pat.test(category)) {
        return false;
      }
    }
  }

  return true;
}

/**
 * Check if a Yutori email is a trivia-focused scout.
 * Matches by filename keyword or HTML category label.
 */
function isTriviaEmail(filename, html) {
  if (/trivia/i.test(filename)) return true;
  const categoryMatch = html.match(
    /text-transform:\s*uppercase[^>]*>\s*<a[^>]*style="[^"]*text-decoration-line:\s*none"[^>]*>([^<]+)<\/a>/i
  );
  if (categoryMatch && /trivia/i.test(categoryMatch[1])) return true;
  return false;
}

/**
 * Preprocess Yutori HTML into clean text optimized for event extraction.
 * Strips email chrome, unwraps tracking URLs, removes boilerplate.
 * Falls back to generic stripHtml if preprocessing produces empty output.
 */
function preprocessYutoriHtml(html) {
  let text = html;

  // Strip everything before first <h3> (email header chrome)
  const h3Index = text.indexOf('<h3');
  if (h3Index > 0) {
    text = text.slice(h3Index);
  }

  // Strip everything after "Report generated by" (footer boilerplate)
  const reportIdx = text.indexOf('Report generated by');
  if (reportIdx > 0) {
    text = text.slice(0, reportIdx);
  }

  // Unwrap Yutori tracking URLs: scouts.yutori.com/api/view?url=ENCODED → inner URL
  text = text.replace(
    /https?:\/\/scouts\.yutori\.com\/api\/view\?url=([^&"'\s]+)[^"'\s]*/gi,
    (_, encoded) => {
      try {
        return decodeURIComponent(encoded);
      } catch {
        return encoded;
      }
    }
  );

  // Convert source link badges to [Source: url] markers
  text = text.replace(
    /<a\s[^>]*href=["']([^"']*(?:ra\.co|eventbrite|instagram|dice\.fm|songkick|brooklynvegan|ohmyrockness|prs\.org|thecitylife)[^"']*)["'][^>]*>.*?<\/a>/gi,
    (_, url) => `[Source: ${url}]`
  );

  // Convert remaining <a href="url">text</a> to "text (url)"
  text = text.replace(/<a\s[^>]*href=["']([^"']*)["'][^>]*>(.*?)<\/a>/gi, (_, url, linkText) => {
    const clean = linkText.replace(/<[^>]*>/g, '').trim();
    if (!clean || clean === url) return url;
    return `${clean} (${url})`;
  });

  // Convert <li> items to [Event] blocks
  text = text.replace(/<li[^>]*>([\s\S]*?)<\/li>/gi, (_, content) => {
    const clean = content
      .replace(/<b[^>]*>(.*?)<\/b>/gi, '$1')
      .replace(/<strong[^>]*>(.*?)<\/strong>/gi, '$1')
      .replace(/<em[^>]*>(.*?)<\/em>/gi, '$1')
      .replace(/<i[^>]*>(.*?)<\/i>/gi, '$1')
      .replace(/<span[^>]*>[\s\S]*?<\/span>/gi, '')
      .replace(/<img[^>]*>/gi, '')
      .replace(/<[^>]*>/g, '')
      .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&#x27;/g, "'")
      .replace(/&nbsp;/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
    if (clean.length < 20) return '';
    return `\n[Event] ${clean}\n`;
  });

  // Convert <h3>, <p>, <strong>/<b> section headers to plain text
  text = text.replace(/<h3[^>]*>(.*?)<\/h3>/gi, '\n## $1\n');
  text = text.replace(/<p[^>]*>(.*?)<\/p>/gi, '\n$1\n');
  text = text.replace(/<b[^>]*>(.*?)<\/b>/gi, '$1');
  text = text.replace(/<strong[^>]*>(.*?)<\/strong>/gi, '$1');

  // Strip remaining HTML tags
  text = text.replace(/<[^>]*>/g, '');

  // Decode entities
  text = text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>');
  text = text.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&#x27;/g, "'");
  text = text.replace(/&nbsp;/g, ' ');

  // Strip boilerplate phrases
  text = text.replace(/\[object Object\]/g, '');
  text = text.replace(/Anything I should adjust\?.*$/gm, '');
  text = text.replace(/Know someone who.*$/gm, '');
  text = text.replace(/Manage Scout/g, '');
  text = text.replace(/Invite them to subscribe/g, '');

  // Collapse whitespace
  text = text.replace(/[ \t]+/g, ' ').replace(/\n{3,}/g, '\n\n').trim();

  // Fall back to generic stripHtml if preprocessing produced empty/tiny output
  if (text.length < 50) {
    return stripHtml(html);
  }
  return text;
}

/**
 * Strip HTML to plain text, preserving <a href> URLs as "text (URL)" format.
 */
function stripHtml(html) {
  return html
    // Convert <a href="url">text</a> to "text (url)"
    .replace(/<a\s[^>]*href=["']([^"']*)["'][^>]*>(.*?)<\/a>/gi, (_, url, text) => {
      const cleanText = text.replace(/<[^>]*>/g, '').trim();
      // If the link text is the URL itself, just keep the URL
      if (cleanText === url || !cleanText) return url;
      return `${cleanText} (${url})`;
    })
    // Convert <br> and block elements to newlines
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/(p|div|h[1-6]|li|tr)>/gi, '\n')
    // Strip remaining tags
    .replace(/<[^>]*>/g, '')
    // Decode common HTML entities
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    // Collapse whitespace but preserve paragraph breaks
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

// === Deterministic trivia parser (P6: deterministic extraction first) ===

/**
 * Known NYC neighborhoods for splitting "Venue Name Neighborhood" text.
 * Sorted by length descending so longest match wins.
 */
const TRIVIA_HOODS = [
  'prospect lefferts gardens', 'bedford stuyvesant',
  'washington heights', 'morningside heights', 'financial district',
  'greenwich village', 'prospect heights', 'brooklyn heights',
  'long island city', 'battery park city',
  'carroll gardens', 'hamilton heights', 'lower east side',
  'upper east side', 'upper west side', 'jackson heights',
  'sheepshead bay', 'brighton beach', 'coney island',
  "hell's kitchen", 'hells kitchen', 'crown heights',
  'windsor terrace', 'borough park', 'bensonhurst',
  'clinton hill', 'midtown east', 'carnegie hill',
  'east village', 'west village', 'south slope', 'sunset park',
  'east harlem', 'ditmas park', 'kensington',
  'park slope', 'murray hill', 'fort greene', 'cobble hill',
  'boerum hill', 'red hook', 'bay ridge', 'kips bay', "kip's bay", 'bed-stuy', 'bowery',
  'williamsburg', 'greenpoint', 'bushwick', 'chelsea', 'gramercy',
  'sunnyside', 'woodside', 'ridgewood', 'elmhurst', 'corona',
  'forest hills', 'rego park', 'kew gardens', 'jamaica', 'bayside',
  'mott haven', 'fordham', 'belmont', 'concourse', 'riverdale',
  'downtown brooklyn', 'midtown', 'harlem', 'astoria', 'tribeca',
  'flatbush', 'midwood', 'flushing', 'gowanus', 'dumbo', 'soho', 'noho',
].sort((a, b) => b.length - a.length);

/**
 * Split "Venue Name Neighborhood" into { venue, neighborhood }.
 * Matches known neighborhoods from the end of the string.
 */
function splitVenueAndHood(text) {
  const lower = text.toLowerCase().trim();
  for (const hood of TRIVIA_HOODS) {
    if (lower.endsWith(' ' + hood) || lower === hood) {
      const cutpoint = text.length - hood.length;
      const venue = text.slice(0, cutpoint).trim();
      const neighborhood = text.slice(cutpoint).trim();
      if (venue.length > 0) return { venue, neighborhood };
    }
  }
  return { venue: text.trim(), neighborhood: null };
}

function parseTo24h(timeStr) {
  const m = timeStr.match(/(\d{1,2}):(\d{2})\s*([AP]M)/i);
  if (!m) return null;
  let hour = parseInt(m[1], 10);
  const min = m[2];
  const ampm = m[3].toUpperCase();
  if (ampm === 'PM' && hour !== 12) hour += 12;
  if (ampm === 'AM' && hour === 12) hour = 0;
  return `${String(hour).padStart(2, '0')}:${min}`;
}

/**
 * Parse time ranges like "7:30 PM", "6:30–9:30 PM", "8:00 PM – 10:00 PM".
 */
function parseTimeRange(str) {
  const m = str.match(/(\d{1,2}:\d{2})\s*([AP]M)?\s*(?:[-–]\s*(\d{1,2}:\d{2})\s*)?([AP]M)?/i);
  if (!m) return { start: null, end: null };
  const [, t1, ampm1, t2, ampm2] = m;
  const startAmPm = (ampm1 || ampm2 || '').toUpperCase();
  const endAmPm = (ampm2 || ampm1 || '').toUpperCase();
  if (!startAmPm) return { start: null, end: null };
  const start = parseTo24h(t1 + ' ' + startAmPm);
  const end = t2 ? parseTo24h(t2 + ' ' + endAmPm) : null;
  return { start, end };
}

const MONTH_MAP = {
  jan: 0, january: 0, feb: 1, february: 1, mar: 2, march: 2,
  apr: 3, april: 3, may: 4, jun: 5, june: 5,
  jul: 6, july: 6, aug: 7, august: 7, sep: 8, september: 8,
  oct: 9, october: 9, nov: 10, november: 10, dec: 11, december: 11,
};

function resolveMonthDay(monthStr, day, refYear) {
  const monthIdx = MONTH_MAP[monthStr.toLowerCase()];
  if (monthIdx === undefined) return null;
  const d = new Date(refYear, monthIdx, parseInt(day, 10));
  if (isNaN(d.getTime())) return null;
  return d.toISOString().slice(0, 10);
}

const DAY_INDICES = {
  sunday: 0, monday: 1, tuesday: 2, wednesday: 3,
  thursday: 4, friday: 5, saturday: 6,
};
const DAY_NAMES_LIST = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

function nextDayOfWeek(dayName, refDate) {
  const target = DAY_INDICES[dayName.toLowerCase()];
  if (target === undefined) return null;
  const ref = new Date(refDate + 'T12:00:00');
  const current = ref.getDay();
  let diff = target - current;
  if (diff < 0) diff += 7;
  ref.setDate(ref.getDate() + diff);
  return ref.toISOString().slice(0, 10);
}

function getDayName(dateStr) {
  const d = new Date(dateStr + 'T12:00:00');
  return DAY_NAMES_LIST[d.getDay()];
}

/**
 * Parse Format A: "Venue Name Neighborhood, Borough Time"
 * Found in NYC Trivia League bulk emails under day-of-week headers.
 */
function parseFormatA(content, currentDate, currentDayName) {
  const m = content.match(/^(.+),\s*(Brooklyn|Manhattan|Queens|Bronx|Staten Island)\s+(\d{1,2}:\d{2}\s*[AP]M)/i);
  if (!m) return null;

  const [, venueAndHood, , timeStr] = m;
  const { venue, neighborhood } = splitVenueAndHood(venueAndHood);
  const startTime = parseTo24h(timeStr);

  const isGameEvent = /trivia|bingo|quiz/i.test(venue);
  const name = isGameEvent
    ? (neighborhood ? `${venue} (${neighborhood})` : venue)
    : (neighborhood ? `Trivia Night at ${venue} (${neighborhood})` : `Trivia Night at ${venue}`);

  return {
    name,
    venue_name: venue,
    venue_address: null,
    neighborhood,
    date_local: currentDate,
    start_time_local: startTime,
    end_time_local: null,
    dayName: currentDayName,
  };
}

/**
 * Parse Format B/D: em-dash separated trivia events.
 * Format B: "Venue — Neighborhood, Borough — [Address] — Day — Time [— recurrence]"
 * Format D: "Venue — Neighborhood, Borough — Day, Date @ Time — Price"
 */
function parseFormatB(content, dayDateMap, baseDate) {
  const segments = content.split(/\s*—\s*/).map(s => s.trim()).filter(Boolean);
  if (segments.length < 3) return null;

  const venue = segments[0];
  const locationInfo = segments[1];
  const refYear = parseInt(baseDate.slice(0, 4), 10);

  let address = null;
  let dayName = null;
  let timeStr = null;
  let explicitDate = null;
  let priceText = null;

  for (let i = 2; i < segments.length; i++) {
    const seg = segments[i].replace(/\.\s*$/, '').trim();
    if (!seg) continue;

    // Combined day+date+time: "Tuesday, Mar 4 @ 7:00 PM"
    const combinedMatch = seg.match(/(\w+day),?\s+(\w+)\s+(\d{1,2})\s*@\s*(.+)/i);
    if (combinedMatch) {
      dayName = combinedMatch[1].toLowerCase();
      explicitDate = resolveMonthDay(combinedMatch[2], combinedMatch[3], refYear);
      timeStr = combinedMatch[4].trim();
      continue;
    }

    if (/^\w+day$/i.test(seg)) {
      dayName = seg.toLowerCase();
    } else if (/\d{1,2}:\d{2}\s*[AP]M/i.test(seg)) {
      timeStr = seg;
    } else if (/^\$/.test(seg) || /^free$/i.test(seg)) {
      priceText = seg;
    } else if (/\d/.test(seg) && seg.length > 10 && !/^yes/i.test(seg)) {
      address = seg;
    }
  }

  if (!dayName && !timeStr) return null;

  const neighborhood = locationInfo.split(',')[0].trim();
  const { start, end } = timeStr ? parseTimeRange(timeStr) : { start: null, end: null };
  const date = explicitDate || (dayName ? (dayDateMap[dayName] || nextDayOfWeek(dayName, baseDate)) : null);

  const isFree = !priceText || /free/i.test(priceText);
  const isGameEvent = /trivia|bingo|quiz/i.test(venue);
  const name = isGameEvent
    ? (neighborhood ? `${venue} (${neighborhood})` : venue)
    : (neighborhood ? `Trivia Night at ${venue} (${neighborhood})` : `Trivia Night at ${venue}`);

  return {
    name,
    venue_name: venue,
    venue_address: address,
    neighborhood,
    date_local: date,
    start_time_local: start,
    end_time_local: end,
    dayName,
    isFree,
    priceText: isFree ? 'Free' : priceText,
  };
}

/**
 * Parse Format E: "Venue (Neighborhood[, Borough]) @ Time [— Price]"
 * Found in "previously reported" sections under day-of-week headers.
 */
function parseFormatE(content, currentDate, currentDayName) {
  const m = content.match(/^(.+?)\s*\(([^)]+)\)\s*@\s*(\d{1,2}:\d{2}\s*[AP]M)/i);
  if (!m) return null;

  const [, venue, hoodBoro, timeStr] = m;
  const neighborhood = hoodBoro.split(',')[0].trim();
  const startTime = parseTo24h(timeStr);

  // Check for price after em-dash
  const priceMatch = content.match(/—\s*(.+)$/);
  const priceText = priceMatch ? priceMatch[1].trim() : null;
  const isFree = !priceText || /free/i.test(priceText);

  const isGameEvent = /trivia|bingo|quiz/i.test(venue);
  const name = isGameEvent
    ? (neighborhood ? `${venue} (${neighborhood})` : venue)
    : (neighborhood ? `Trivia Night at ${venue} (${neighborhood})` : `Trivia Night at ${venue}`);

  return {
    name,
    venue_name: venue.trim(),
    venue_address: null,
    neighborhood,
    date_local: currentDate,
    start_time_local: startTime,
    end_time_local: null,
    dayName: currentDayName,
    isFree,
    priceText: isFree ? 'Free' : priceText,
  };
}

/**
 * Parse Format C: "Event Name — Location, Address; Day, Time; Next: Date"
 * Found in upcoming picks emails with explicit next-occurrence dates.
 */
function parseFormatC(content, refYear) {
  const m = content.match(
    /^(.+?)\s*—\s*(.+?);\s*(?:\d+(?:st|nd|rd|th)\s+)?(\w+day),?\s*(.+?);\s*Next:\s*(.+)$/i
  );
  if (!m) return null;

  const [, eventName, locationInfo, dayName, timeStr, nextDateStr] = m;

  // Parse "Next: March 6, 2026"
  const nextMatch = nextDateStr.match(/(\w+)\s+(\d{1,2}),?\s*(\d{4})?/);
  let date = null;
  if (nextMatch) {
    date = resolveMonthDay(nextMatch[1], nextMatch[2], nextMatch[3] ? parseInt(nextMatch[3]) : refYear);
  }

  const locParts = locationInfo.split(',').map(s => s.trim());
  const neighborhood = locParts[0];
  const address = locParts.length > 1 ? locParts.slice(1).join(', ').trim() : null;

  // Extract venue from "X at VENUE" pattern
  const atMatch = eventName.match(/\bat\s+(.+)$/i);
  const venueName = atMatch ? atMatch[1].trim() : null;

  const { start, end } = parseTimeRange(timeStr);

  return {
    name: eventName.trim(),
    venue_name: venueName || eventName.trim(),
    venue_address: address,
    neighborhood,
    date_local: date,
    start_time_local: start,
    end_time_local: end,
    dayName: dayName.toLowerCase(),
  };
}

/**
 * Deterministically parse trivia events from preprocessed Yutori text.
 * Handles three formats: A (bulk venue list), B (em-dash separated), C (semicolon + Next: date).
 */
function parseTriviaEvents(text, filename) {
  const baseDateMatch = filename.match(/^(\d{4}-\d{2}-\d{2})/);
  const baseDate = baseDateMatch ? baseDateMatch[1] : null;
  if (!baseDate) return [];
  const refYear = parseInt(baseDate.slice(0, 4), 10);

  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  const events = [];
  let currentDate = null;
  let currentDayName = null;

  // Pass 1: Build day header → date map from explicit headers ("Tuesday, Feb 24")
  const dayDateMap = {};
  for (const line of lines) {
    const m = line.match(/^(?:##\s*)?(\w+day),?\s+(\w+)\s+(\d{1,2})\b/i);
    if (m) {
      const resolved = resolveMonthDay(m[2], m[3], refYear);
      if (resolved) dayDateMap[m[1].toLowerCase()] = resolved;
    }
  }

  // Pass 2: Parse events
  for (const line of lines) {
    // Day headers
    const headerMatch = line.match(/^(?:##\s*)?(\w+day),?\s+(\w+)\s+(\d{1,2})\b/i);
    if (headerMatch) {
      currentDate = resolveMonthDay(headerMatch[2], headerMatch[3], refYear);
      currentDayName = headerMatch[1].toLowerCase();
      continue;
    }

    if (!line.startsWith('[Event]')) continue;

    const content = line.replace(/^\[Event\]\s*/, '').replace(/\.\s*\.?\s*$/, '').trim();
    if (!content || content.length < 10) continue;

    // Skip metadata/summary lines
    if (/^(Entry fee|Registration|Format:|Prizes|Most events|Themed nights|Weekly recurring|21\+ requirement|Earliest upcoming|Event:|Day & time:|Locations:|Team size:)/i.test(content)) continue;

    let event = null;

    const hasEmDash = content.includes('\u2014');
    const hasNextDate = /;\s*Next:/i.test(content);

    if (hasEmDash && hasNextDate) {
      event = parseFormatC(content, refYear);
    } else if (hasEmDash) {
      event = parseFormatB(content, dayDateMap, baseDate);
      // Format B returns null for 2-segment lines — try Format E
      if (!event) {
        event = parseFormatE(content, currentDate, currentDayName);
      }
    } else {
      event = parseFormatE(content, currentDate, currentDayName);
      if (!event) {
        event = parseFormatA(content, currentDate, currentDayName);
      }
    }

    if (!event) continue;

    const dayName = event.dayName || (event.date_local ? getDayName(event.date_local) : null);
    const isFree = event.isFree !== false;

    events.push({
      name: event.name,
      venue_name: event.venue_name,
      venue_address: event.venue_address || null,
      neighborhood: event.neighborhood,
      date_local: event.date_local,
      start_time_local: event.start_time_local,
      end_time_local: event.end_time_local,
      is_free: isFree,
      price_display: event.priceText || (isFree ? 'Free' : null),
      category: 'trivia',
      extraction_confidence: 0.95,
      source_url: null,
      is_recurring: true,
      recurrence_day: dayName,
      recurrence_time: event.start_time_local,
      evidence: {
        name_quote: event.name ? event.name.toLowerCase() : null,
        time_quote: event.start_time_local || null,
        location_quote: event.venue_name ? event.venue_name.toLowerCase() : null,
        price_quote: event.priceText || (isFree ? 'free' : null),
      },
    });
  }

  return events;
}

// === Deterministic general event parser (P6: deterministic extraction first) ===

/**
 * Tag-to-category mapping for Yutori event tags (uppercase bracket tags like [35MM], [Q&A]).
 */
const TAG_TO_CATEGORY = [
  { pattern: /REPERTORY|RESTORED PRINT|35MM|MIDNIGHT|PREMIERE|SERIES|CULT|DOCUMENTARY|ANIME|MARATHON|INTERNATIONAL|ANNIVERSARY/i, category: 'art', subcategory: 'film' },
  { pattern: /COMEDY|STAND-UP|IMPROV/i, category: 'comedy', subcategory: null },
  { pattern: /DJ|DANCE|RAVE/i, category: 'nightlife', subcategory: null },
];

/**
 * Infer category from the full event line text when tags aren't present.
 */
function inferCategory(text) {
  const lower = text.toLowerCase();
  if (/\b(?:screening|cinema|repertory|35mm|restored?\s*print|midnight\s*show|film\s*forum|metrograph|nitehawk|ifc center|spectacle)\b/.test(lower)) return { category: 'art', subcategory: 'film' };
  if (/\b(?:stand-?up|improv|comedy)\b/.test(lower)) return { category: 'comedy', subcategory: null };
  if (/\b(?:listening\s*session)\b/.test(lower)) return { category: 'music', subcategory: 'listening' };
  if (/\b(?:dj\b|techno|house\s*music|rave|dance\s*party|dancehall|edm|underground\s*(?:edm|techno))\b/.test(lower)) return { category: 'nightlife', subcategory: null };
  if (/\b(?:jazz|concert|live\s*music|album\s*release|indie\s*rock|songwriter|kora)\b/.test(lower)) return { category: 'music', subcategory: null };
  if (/\b(?:art\s*opening|gallery|exhibition|installation)\b/.test(lower)) return { category: 'art', subcategory: null };
  if (/\b(?:book\s*launch|reading|literary|poetry)\b/.test(lower)) return { category: 'art', subcategory: 'literary' };
  if (/\b(?:listening\s*session)\b/.test(lower)) return { category: 'music', subcategory: 'listening' };
  return { category: 'other', subcategory: null };
}

/**
 * Extract venue name and address from a text fragment.
 * Splits on the first street-number boundary: "Mercury Lounge 217 E 10th St" → venue + addr.
 */
function splitVenueAddress(venueStr) {
  // Clean trailing borough/neighborhood references
  const cleaned = venueStr.replace(/,\s*(?:Brooklyn|Manhattan|Queens|Bronx|Staten Island|New York|NY)(?:\s*,?\s*(?:NY)?\s*\d{5})?.*$/i, '').trim();

  // Try splitting on comma + street number: "Paragon, 990 Broadway"
  const commaSplit = cleaned.match(/^(.+?),\s*(\d+\s+.+)$/);
  if (commaSplit) return { venue: commaSplit[1].trim(), address: commaSplit[2].trim() };

  // Try splitting on space + street number: "Metrograph 7 Ludlow St"
  const spaceSplit = cleaned.match(/^(.+?)\s+(\d+\s+\w+.*)$/);
  if (spaceSplit && spaceSplit[1].length >= 2) return { venue: spaceSplit[1].trim(), address: spaceSplit[2].trim() };

  // Try splitting on number run-on: "LunÀtico486 Halsey Street"
  const runOn = cleaned.match(/^([^\d]+?)(\d+\s+.+)$/);
  if (runOn && runOn[1].length >= 2) return { venue: runOn[1].trim(), address: runOn[2].trim() };

  return { venue: cleaned, address: null };
}

/**
 * Parse a single [Event] line into structured event fields.
 * Uses ordered heuristics — works across numbered, venue-colon, em-dash, and field-labeled formats.
 *
 * @param {string} line - The full [Event] line including prefix
 * @param {string} fallbackDate - YYYY-MM-DD to use when no date found in line
 * @returns {object|null} Parsed event or null if line is not a parseable event
 */
function parseGeneralEventLine(line, fallbackDate) {
  let text = line.replace(/^\[Event\]\s*/, '').trim();
  text = text.replace(/^\d+[.)]\s*/, '');        // Strip number prefix
  text = text.replace(/\.\s*\.?\s*$/, '').trim(); // Strip trailing dots

  // --- Skip conditions ---
  if (text.length < 20) return null;
  if (/^(?:Full details|Don't Miss|Full Screening Log|Coming Up:)/i.test(text)) return null;
  if (/^(?:Date & time|Venue|Event type|Entry|Tickets):\s/i.test(text)) return null;
  if (/^(?:Entry fee|Registration|Format:|Prizes|Most events|Themed nights|Weekly recurring)/i.test(text)) return null;
  // Skip aggregate/prose lines (venue hosts "multiple..." or long sentences without structured data)
  if (/\bhosts?\s+multiple\b/i.test(text)) return null;
  // Skip lines that are clearly analysis/commentary (fintech leak-through)
  if (/\b(?:raises the bar|signaling|reframing|positioning|signals?)\b/i.test(text) && !/\b(?:PM|AM|\$\d)/i.test(text)) return null;

  const refYear = fallbackDate ? parseInt(fallbackDate.slice(0, 4), 10) : new Date().getFullYear();

  // === Extract fields in order, removing matched text to avoid re-matching ===

  // 1. Extract tags: [UPPERCASE CONTENT]
  const tags = [];
  text = text.replace(/\[([A-Z][A-Z0-9\s&/'–-]+)\]/g, (_, tag) => {
    tags.push(tag.trim());
    return ' ';
  });

  // 2. Extract price
  let price = null;
  let isFree = false;
  const priceMatch = text.match(/\$\d+(?:\.\d{1,2})?(?:\s*[-–]\s*\$?\d+(?:\.\d{1,2})?)?/);
  if (priceMatch) {
    price = priceMatch[0];
    text = text.slice(0, priceMatch.index) + ' ' + text.slice(priceMatch.index + priceMatch[0].length);
  }
  if (!price) {
    const freeMatch = text.match(/\b(Free(?:\s+(?:RSVP|admission|entry))?)\b/i);
    if (freeMatch) {
      price = freeMatch[1];
      isFree = true;
      text = text.slice(0, freeMatch.index) + ' ' + text.slice(freeMatch.index + freeMatch[0].length);
    }
  }
  if (price && /free/i.test(price)) isFree = true;

  // 3. Extract ticket URL (labeled or bare)
  let ticketUrl = null;
  const labeledUrlMatch = text.match(/(?:Tickets|Details|Info|Series|Purchase page|Tournament listings)(?:\s*(?:and info)?(?:\s*via\s+[^(]+)?)?\s*[:.]?\s*(https?:\/\/\S+)/i);
  if (labeledUrlMatch) {
    ticketUrl = labeledUrlMatch[1].replace(/[.,;)]+$/, '');
    text = text.slice(0, labeledUrlMatch.index) + ' ' + text.slice(labeledUrlMatch.index + labeledUrlMatch[0].length);
  } else {
    const bareUrlMatch = text.match(/(https?:\/\/\S+)/);
    if (bareUrlMatch) {
      ticketUrl = bareUrlMatch[1].replace(/[.,;)]+$/, '');
      text = text.slice(0, bareUrlMatch.index) + ' ' + text.slice(bareUrlMatch.index + bareUrlMatch[0].length);
    }
  }

  // 4. Extract time: H:MM AM/PM with optional end time
  // First neutralize "doors close/ends at" times so they don't get picked as start time
  let startTime = null;
  let endTime = null;
  const timeText = text.replace(/(?:close[sd]?|ends?|closing|doors?\s+close)\s+\d{1,2}:\d{2}\s*[AP]M/gi, '');
  const timeMatch = timeText.match(/(\d{1,2}:\d{2})\s*([AP]M)\s*(?:[-–]\s*(\d{1,2}:\d{2})\s*([AP]M))?/i);
  if (timeMatch) {
    startTime = parseTo24h(timeMatch[1] + ' ' + timeMatch[2]);
    if (timeMatch[3] && timeMatch[4]) endTime = parseTo24h(timeMatch[3] + ' ' + timeMatch[4]);
    // Remove the matched time from original text (find same pattern in original)
    const origTimeMatch = text.match(/(\d{1,2}:\d{2})\s*([AP]M)\s*(?:[-–]\s*(\d{1,2}:\d{2})\s*([AP]M))?/i);
    if (origTimeMatch && parseTo24h(origTimeMatch[1] + ' ' + origTimeMatch[2]) !== startTime) {
      // First match in original was the "close" time — find and remove the real start time
      const afterClose = text.slice(origTimeMatch.index + origTimeMatch[0].length);
      const realMatch = afterClose.match(/(\d{1,2}:\d{2})\s*([AP]M)\s*(?:[-–]\s*(\d{1,2}:\d{2})\s*([AP]M))?/i);
      if (realMatch) {
        const realIdx = origTimeMatch.index + origTimeMatch[0].length + realMatch.index;
        text = text.slice(0, realIdx) + ' ' + text.slice(realIdx + realMatch[0].length);
      }
    } else if (origTimeMatch) {
      text = text.slice(0, origTimeMatch.index) + ' ' + text.slice(origTimeMatch.index + origTimeMatch[0].length);
    }
  }

  // 5. Extract date: "Day Mon DD[, YYYY]" or "Month DD[, YYYY]"
  let dateLocal = null;
  const datePatterns = [
    /(?:(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\w*,?\s+)?(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w*\s+(\d{1,2})(?:,?\s*(\d{4}))?/i,
    /(?:(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),?\s+)?(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})(?:,?\s*(\d{4}))?/i,
  ];
  for (const pat of datePatterns) {
    const dateMatch = text.match(pat);
    if (dateMatch) {
      dateLocal = resolveMonthDay(dateMatch[1], dateMatch[2], dateMatch[3] ? parseInt(dateMatch[3], 10) : refYear);
      if (dateLocal) {
        text = text.slice(0, dateMatch.index) + ' ' + text.slice(dateMatch.index + dateMatch[0].length);
        break;
      }
    }
  }
  if (!dateLocal) dateLocal = fallbackDate;

  // 6. Extract quoted title
  let name = null;
  const quotedMatch = line.match(/"([^"]+)"/);
  if (quotedMatch) {
    name = quotedMatch[1].trim();
  }

  // 7. Extract venue + address
  let venueName = null;
  let venueAddress = null;

  // Pattern A: For quoted titles, find 'at Venue' after the closing quote in original line
  if (name) {
    const quoteEnd = line.indexOf('"', line.indexOf('"' + name) + name.length + 1);
    if (quoteEnd !== -1) {
      const afterQuote = line.slice(quoteEnd + 1);
      const atAfter = afterQuote.match(/^\s*at\s+(.+?)(?:\s+(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\w*[\s,]|\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w*\s|\s*—|\s*$)/i);
      if (atAfter) {
        const raw = atAfter[1].trim().replace(/\.\s*$/, '');
        const { venue, address } = splitVenueAddress(raw);
        if (venue.length >= 2) { venueName = venue; venueAddress = address; }
      }
    }
  }

  // Pattern B: "at VenueInfo" in remaining text (em-dash and other formats)
  if (!venueName) {
    const atMatch = text.match(/\bat\s+([A-Z][^—;]+?)(?:\s*[—;.]|\s*$)/i);
    if (atMatch) {
      const raw = atMatch[1].trim().replace(/\.\s*$/, '');
      const { venue, address } = splitVenueAddress(raw);
      if (venue.length >= 2) { venueName = venue; venueAddress = address; }
    }
  }

  // Pattern C: "Venue: Name, Address" (field-labeled format)
  if (!venueName) {
    const venueKV = text.match(/Venue:\s*([^,;]+)(?:,\s*(.+?))?(?:[.;]|$)/i);
    if (venueKV) {
      venueName = venueKV[1].trim();
      if (venueKV[2]) {
        venueAddress = venueKV[2].trim().replace(/,\s*(?:NY|New York|Brooklyn|Manhattan|Queens|Bronx)(?:\s*,?\s*(?:NY)?\s*\d{5})?.*$/i, '').trim();
      }
    }
  }

  // Pattern D: "VenueName:" prefix (venue-colon format like "Metrograph: ...")
  if (!venueName) {
    const colonMatch = text.match(/^([A-Z][^:—"]{2,40}):\s/);
    if (colonMatch) {
      venueName = colonMatch[1].trim();
    }
  }

  // Pattern E: Standalone "VenueName, NNN Street" after date/time removal
  if (!venueName) {
    const standaloneMatch = text.match(/(?:^|[.;]\s*)([A-Z][A-Za-z\s']+?),\s*(\d+(?:-\d+)?\s+(?:\w+\s*)+(?:St|Street|Ave|Avenue|Blvd|Boulevard|Rd|Road|Way|Pl|Place|Broadway|Parkway)\b[^.;]*)/i);
    if (standaloneMatch) {
      venueName = standaloneMatch[1].trim();
      venueAddress = standaloneMatch[2].trim().replace(/,\s*(?:Brooklyn|Manhattan|Queens|Bronx|New York|NY).*$/i, '').trim();
    }
  }

  // Pattern F: Parenthetical venue "(Venue Name, Date Range)"
  if (!venueName && !name) {
    const parenVenue = line.match(/\(([^)]+?),\s*(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)/i);
    if (parenVenue) {
      venueName = parenVenue[1].trim();
    }
  }

  // 8. Extract neighborhood from known list
  let neighborhood = null;
  const searchText = (text + ' ' + (venueAddress || '')).toLowerCase();
  for (const hood of TRIVIA_HOODS) {
    const idx = searchText.indexOf(hood);
    if (idx !== -1) {
      const before = idx > 0 ? searchText[idx - 1] : ' ';
      const after = idx + hood.length < searchText.length ? searchText[idx + hood.length] : ' ';
      if (/[\s,.(]/.test(before) && /[\s,.):;]/.test(after)) {
        neighborhood = hood.split(/\s+/).map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
        break;
      }
    }
  }

  // 9. Unquoted name (if no quoted title found)
  if (!name) {
    const stripped = line.replace(/^\[Event\]\s*/, '').replace(/^\d+[.)]\s*/, '').trim();
    // Try first segment before em-dash
    const dashParts = stripped.split(/\s*—\s*/);
    if (dashParts.length >= 2 && dashParts[0].length >= 5) {
      name = dashParts[0].replace(/\.\s*$/, '').trim();
    } else {
      // Use first clause before semicolon or period
      name = stripped.split(/[;.]/)[0].trim().slice(0, 120);
    }
  }

  if (!name || name.length < 5) return null;

  // Truncate long names at a natural break (100 chars max)
  if (name.length > 100) {
    const breakMatch = name.slice(0, 100).match(/^(.{40,}?)(?:\s*[-–—;,]\s)/);
    name = breakMatch ? breakMatch[1].trim() : name.slice(0, 100).trim();
  }

  // 10. Infer category
  let category = null;
  let subcategory = null;
  const tagStr = tags.join(' ');
  for (const { pattern, category: cat, subcategory: sub } of TAG_TO_CATEGORY) {
    if (pattern.test(tagStr)) {
      category = cat;
      subcategory = sub;
      break;
    }
  }
  if (!category) {
    const inferred = inferCategory(line);
    category = inferred.category;
    subcategory = inferred.subcategory;
  }

  // Confidence based on extracted fields
  const fieldCount = [name, venueName, dateLocal, startTime].filter(Boolean).length;
  const confidence = fieldCount >= 4 ? 0.9 : fieldCount >= 3 ? 0.8 : 0.7;

  // Build description from remaining text
  const remaining = text.replace(/\s+/g, ' ').trim();
  const description = remaining.length > 20 ? remaining.slice(0, 200).trim() : null;

  return {
    name,
    venue_name: venueName,
    venue_address: venueAddress,
    neighborhood,
    date_local: dateLocal,
    start_time_local: startTime,
    end_time_local: endTime,
    is_free: isFree,
    price_display: price,
    category,
    subcategory,
    extraction_confidence: confidence,
    source_url: ticketUrl,
    description_short: description,
    evidence: {
      name_quote: name ? name.toLowerCase() : null,
      time_quote: startTime || null,
      location_quote: venueName ? venueName.toLowerCase() : null,
      price_quote: price ? price.toLowerCase() : null,
    },
  };
}

/**
 * Parse non-trivia events from preprocessed Yutori text.
 * Extracts [Event] lines and runs the general parser on each.
 *
 * @param {string} text - Preprocessed Yutori email text
 * @param {string} filename - Email filename (e.g., "2026-02-25-scout-...")
 * @returns {object[]} Array of parsed events
 */
function parseNonTriviaEvents(text, filename) {
  const baseDateMatch = filename.match(/^(\d{4}-\d{2}-\d{2})/);
  const fallbackDate = baseDateMatch ? baseDateMatch[1] : null;
  if (!fallbackDate) return [];

  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  const events = [];

  for (const line of lines) {
    if (!line.startsWith('[Event]')) continue;
    const event = parseGeneralEventLine(line, fallbackDate);
    if (event) events.push(event);
  }

  return events;
}

/**
 * Load cached events from previously processed briefings.
 */
function loadCachedEvents() {
  try {
    if (fs.existsSync(CACHE_FILE)) {
      const data = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8'));
      if (data?.events) backfillEvidence(data.events);
      return data;
    }
  } catch (err) {
    console.warn('Yutori: failed to load cached-events.json:', err.message);
  }
  return null;
}

/**
 * Save extracted events, accumulating with previously cached events.
 * Dedupes by event ID and prunes events >30 days in the past.
 */
function saveCachedEvents(newEvents) {
  try {
    fs.mkdirSync(YUTORI_DIR, { recursive: true });

    // Load existing cached events and merge
    const existing = loadCachedEvents();
    const existingEvents = existing?.events || [];
    const seen = new Set(newEvents.map(e => e.id));
    const kept = existingEvents.filter(e => !seen.has(e.id));
    const merged = [...newEvents, ...kept];

    // Prune events with dates >30 days in the past
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - 30);
    const cutoffStr = cutoff.toISOString().slice(0, 10);
    const pruned = merged.filter(e => {
      const d = e.date_local;
      if (!d) return true; // keep undated events
      return d >= cutoffStr;
    });

    fs.writeFileSync(CACHE_FILE, JSON.stringify({ events: pruned, timestamp: Date.now() }, null, 2));
  } catch (err) {
    console.warn('Yutori: failed to save cached-events.json:', err.message);
  }
}

/**
 * Load the set of already-processed Gmail message IDs.
 */
function loadProcessedIds() {
  try {
    if (fs.existsSync(PROCESSED_IDS_FILE)) {
      return new Set(JSON.parse(fs.readFileSync(PROCESSED_IDS_FILE, 'utf8')));
    }
  } catch (err) {
    console.warn('Yutori: failed to load processed-ids.json:', err.message);
  }
  return new Set();
}

/**
 * Save the set of processed Gmail message IDs.
 */
function saveProcessedIds(ids) {
  try {
    fs.mkdirSync(YUTORI_DIR, { recursive: true });
    fs.writeFileSync(PROCESSED_IDS_FILE, JSON.stringify([...ids], null, 2));
  } catch (err) {
    console.warn('Yutori: failed to save processed-ids.json:', err.message);
  }
}

/**
 * Create a filename slug from a subject and date string.
 */
function makeFilename(subject, dateStr) {
  const date = dateStr ? new Date(dateStr) : new Date();
  const ymd = isNaN(date.getTime()) ? new Date().toISOString().slice(0, 10) : date.toISOString().slice(0, 10);
  const slug = (subject || 'briefing')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);
  return `${ymd}-${slug}.html`;
}

/**
 * Fetch Yutori emails from Gmail and save new ones to data/yutori/ as .html files.
 * Returns the number of new emails saved.
 */
async function ingestFromGmail() {
  const emails = await fetchYutoriEmails(48);
  if (emails.length === 0) {
    return 0;
  }

  const processedIds = loadProcessedIds();
  fs.mkdirSync(YUTORI_DIR, { recursive: true });

  let saved = 0;
  for (const email of emails) {
    if (processedIds.has(email.id)) {
      continue;
    }

    const filename = makeFilename(email.subject, email.date);
    const filepath = path.join(YUTORI_DIR, filename);

    // Skip if a file with this name already exists (from manual placement or prior run)
    if (fs.existsSync(filepath)) {
      processedIds.add(email.id);
      continue;
    }

    try {
      fs.writeFileSync(filepath, email.body, 'utf8');
      processedIds.add(email.id);
      saved++;
      console.log(`Yutori: saved Gmail email → ${filename}`);
    } catch (err) {
      console.warn(`Yutori: failed to save ${filename}:`, err.message);
    }
  }

  saveProcessedIds(processedIds);
  return saved;
}

/**
 * Scan extracted events for recurrence markers and upsert into recurring_patterns table.
 */
function processRecurrencePatterns(events) {
  const recurring = events.filter(e => e._raw?.is_recurring && e._raw?.recurrence_day);
  if (recurring.length === 0) return;

  try {
    const { upsertPattern } = require('../db');
    let count = 0;
    for (const e of recurring) {
      upsertPattern({
        name: e.name,
        venue_name: e.venue_name || 'TBA',
        venue_address: e.venue_address || null,
        neighborhood: e.neighborhood || null,
        day_of_week: e._raw.recurrence_day,
        time_local: e._raw.recurrence_time || null,
        end_time_local: null,
        category: e.category || null,
        subcategory: e.subcategory || null,
        is_free: e.is_free || false,
        price_display: e.price_display || null,
        description_short: e.description_short || null,
        source_name: 'yutori',
        source_url: e.source_url || null,
        ticket_url: e.ticket_url || null,
        extraction_confidence: e.extraction_confidence ?? null,
        last_confirmed: new Date().toISOString().slice(0, 10),
      });
      count++;
    }
    if (count > 0) {
      console.log(`Yutori: ${count} recurring patterns upserted`);
    }
  } catch (err) {
    // SQLite not available — skip pattern detection
    if (err.code !== 'MODULE_NOT_FOUND') {
      console.warn('Yutori: failed to upsert recurring patterns:', err.message);
    }
  }
}

async function fetchYutoriEvents({ reprocess = false } = {}) {
  console.log('Fetching Yutori agent briefings...');
  try {
    // Step 1: Try fetching from Gmail (no-op if credentials not configured)
    const gmailCount = await ingestFromGmail();
    if (gmailCount > 0) {
      console.log(`Yutori: ${gmailCount} new email(s) from Gmail`);
    }

    // Reprocess: move all processed files back and clear stale cache
    if (reprocess && fs.existsSync(PROCESSED_DIR)) {
      const processed = fs.readdirSync(PROCESSED_DIR).filter(f => /\.(txt|html?)$/i.test(f));
      if (processed.length > 0) {
        fs.mkdirSync(YUTORI_DIR, { recursive: true });
        console.log(`Yutori: reprocessing ${processed.length} files from processed/`);
        for (const f of processed) {
          fs.renameSync(path.join(PROCESSED_DIR, f), path.join(YUTORI_DIR, f));
        }
        if (fs.existsSync(CACHE_FILE)) fs.unlinkSync(CACHE_FILE);
      }
    }

    // Step 2: Process files in data/yutori/ (from Gmail or manual placement)
    if (!fs.existsSync(YUTORI_DIR)) {
      console.log('Yutori: data/yutori/ directory not found, skipping');
      return [];
    }

    const files = fs.readdirSync(YUTORI_DIR)
      .filter(f => /\.(txt|html?)$/i.test(f))
      .sort();

    if (files.length === 0) {
      // No new files — return cached events from last extraction
      const cached = loadCachedEvents();
      if (cached?.events?.length > 0) {
        console.log(`Yutori: returning ${cached.events.length} cached events (no new files)`);
        return cached.events;
      }

      // No cache exists — bootstrap by re-processing most recent file from processed/
      if (fs.existsSync(PROCESSED_DIR)) {
        const processed = fs.readdirSync(PROCESSED_DIR)
          .filter(f => /\.(txt|html?)$/i.test(f))
          .sort();
        if (processed.length > 0) {
          const latest = processed[processed.length - 1];
          console.log(`Yutori: bootstrapping cache from processed/${latest}`);
          // Move latest back to main dir for processing
          fs.renameSync(path.join(PROCESSED_DIR, latest), path.join(YUTORI_DIR, latest));
          // Re-run — will find the file, process it, cache, and move back
          return fetchYutoriEvents({ reprocess: false });
        }
      }

      console.log('Yutori: no briefing files found and no cache');
      return [];
    }

    // Process each file individually to stay within extraction limits
    const fileContents = [];
    const triviaEvents = [];
    for (const file of files) {
      const raw = fs.readFileSync(path.join(YUTORI_DIR, file), 'utf8');

      // Skip non-event emails (fintech, sports, etc.)
      if (/\.html?$/i.test(file) && !isEventEmail(file, raw)) {
        console.log(`Yutori: skipping non-event email → ${file}`);
        continue;
      }

      // Trivia emails: deterministic parse (P6), skip LLM
      if (/\.html?$/i.test(file) && isTriviaEmail(file, raw)) {
        const content = preprocessYutoriHtml(raw);
        const parsed = parseTriviaEvents(content, file);
        if (parsed.length > 0) {
          console.log(`Yutori: deterministic trivia parse → ${parsed.length} events from ${file}`);
          captureExtractionInput('yutori', content, null);
          const normalized = parsed
            .map(e => normalizeExtractedEvent(e, 'yutori', 'aggregator', 0.8))
            .filter(e => e.name && e.completeness >= 0.35);
          triviaEvents.push(...normalized);
          continue;
        }
        // Fall through to LLM if deterministic parse found nothing
      }

      // Non-trivia event emails: try deterministic parse first (P6)
      if (/\.html?$/i.test(file)) {
        const content = preprocessYutoriHtml(raw);
        const parsed = parseNonTriviaEvents(content, file);
        const eventLineCount = content.split('\n').filter(l => l.trim().startsWith('[Event]')).length;

        if (parsed.length > 0 && eventLineCount > 0 && parsed.length >= eventLineCount * 0.4) {
          // Deterministic parse captured enough — skip LLM
          console.log(`Yutori: deterministic parse → ${parsed.length}/${eventLineCount} events from ${file}`);
          captureExtractionInput('yutori', content, null);
          const normalized = parsed
            .map(e => normalizeExtractedEvent(e, 'yutori', 'aggregator', 0.8))
            .filter(e => e.name && e.completeness >= 0.25);
          triviaEvents.push(...normalized);
          continue;
        }
        // Fall through to LLM if deterministic parse got < 40% of event lines
      }

      const content = /\.html?$/i.test(file) ? preprocessYutoriHtml(raw) : raw;
      if (content.length >= 50) {
        fileContents.push({ file, content });
      }
    }

    if (fileContents.length === 0 && triviaEvents.length === 0) {
      console.log('Yutori: all briefing files too short or empty, skipping');
      return [];
    }

    console.log(`Yutori: processing ${fileContents.length} files + ${triviaEvents.length} trivia-parsed events`);
    const events = [...triviaEvents];

    // Process files in parallel (max 3 concurrent to avoid rate limits)
    const CONCURRENCY = 3;
    for (let i = 0; i < fileContents.length; i += CONCURRENCY) {
      const batch = fileContents.slice(i, i + CONCURRENCY);
      const results = await Promise.allSettled(
        batch.map(async ({ file, content }) => {
          console.log(`Yutori: extracting ${file} (${content.length} chars)`);
          const preamble = `[YUTORI CONTEXT]\nThis is a curated Yutori agent briefing about NYC events.\nEach event typically has: name, description, date/time, venue, address, price, source URL.\nExtract ALL events — including listening sessions, art openings, comedy, trivia, and small one-offs.\n\nRECURRENCE DETECTION:\nMany Yutori events are recurring weekly. Look for:\n- "every [day]", "weekly", "[day]s at [time]"\n- "Next: [date]" with a day-of-week pattern\n- Trivia nights, open mics, DJ residencies are often recurring\nSet is_recurring=true, recurrence_day, and recurrence_time when detected.\n[END CONTEXT]\n\n`;
          const enrichedContent = preamble + content;
          captureExtractionInput('yutori', enrichedContent, null);
          const result = await extractEvents(enrichedContent, 'yutori', null);
          const raw = result.events || [];
          const normalized = raw.map(e => normalizeExtractedEvent(e, 'yutori', 'aggregator', 0.8));
          const passed = normalized.filter(e => e.name && e.completeness >= 0.25);
          // Drop prose advice/commentary with no structural event signals.
          // date_local alone doesn't count — the LLM assigns today's date to everything.
          // Require at least one of: specific time, real venue, or URL.
          // A venue that's a substring of the event name (or vice versa) is fabricated.
          const contentFiltered = passed.filter(e => {
            const hasTime = !!e.start_time_local;
            const hasUrl = !!e.ticket_url || !!e.source_url;
            let hasVenue = !!e.venue_name && e.venue_name !== 'TBA';
            if (hasVenue) {
              const vLow = e.venue_name.toLowerCase();
              const nLow = (e.name || '').toLowerCase();
              if (nLow.startsWith(vLow) || vLow.startsWith(nLow.split(':')[0])) {
                hasVenue = false;
              }
            }
            if (!hasTime && !hasVenue && !hasUrl) return false;
            return true;
          });
          const dropped = raw.length - contentFiltered.length;
          if (dropped > 0) {
            console.log(`Yutori: LLM extracted ${raw.length} from ${file}, ${contentFiltered.length} passed gates (${dropped} dropped)`);
          }
          return contentFiltered;
        })
      );
      for (const r of results) {
        if (r.status === 'fulfilled') {
          events.push(...r.value);
        } else {
          console.warn('Yutori: extraction failed for batch item:', r.reason?.message);
        }
      }
    }

    // Move processed files to processed/ directory
    fs.mkdirSync(PROCESSED_DIR, { recursive: true });
    for (const file of files) {
      const src = path.join(YUTORI_DIR, file);
      const dest = path.join(PROCESSED_DIR, file);
      try {
        fs.renameSync(src, dest);
      } catch (err) {
        console.warn(`Yutori: failed to move ${file}: ${err.message}`);
      }
    }

    // Detect recurring patterns and upsert to SQLite
    processRecurrencePatterns(events);

    saveCachedEvents(events);
    console.log(`Yutori: ${events.length} events from ${files.length} briefings`);
    return events;
  } catch (err) {
    console.error('Yutori error:', err.message);
    return [];
  }
}

module.exports = { fetchYutoriEvents, stripHtml, preprocessYutoriHtml, isEventEmail, isTriviaEmail, parseTriviaEvents, parseGeneralEventLine, parseNonTriviaEvents };
