const { parseStructuredYutoriHtml } = require('../../src/sources/yutori/structured-parser');

describe('parseStructuredYutoriHtml', () => {
  describe('Template A: inline <li> with source badge', () => {
    const html = `
      <h3>Test Email</h3>
      <p><b style="font-weight:700">Electronic music — immediate</b></p>
      <ul>
        <li style="color:rgb(51,65,85)">Dweller Thursday: Moor Mother b2b Hieroglyphic Being at Paragon, 990 Broadway, Brooklyn — Thu, Feb 19, 9:30 PM–3:00 AM. <span style="display:inline-block"><a href="https://scouts.yutori.com/api/view?url=https%3A%2F%2Fra.co%2Fevents%2F2354432&amp;referrer=email&amp;scout_id=abc&amp;destination=source"><img src="favicon"/><span>Event details</span></a></span>.</li>
        <li style="color:rgb(51,65,85)">Techno Tribe presents: Reflection at Rash, 941 Willoughby Ave, Brooklyn — Fri, Feb 20, 10:00 PM–4:00 AM. $15. <span style="display:inline-block"><a href="https://scouts.yutori.com/api/view?url=https%3A%2F%2Fra.co%2Fevents%2F2354819&amp;referrer=email&amp;scout_id=abc&amp;destination=source"><img src="favicon"/><span>Event details</span></a></span>.</li>
      </ul>
      <p>Report generated by 191 agents</p>
    `;

    test('extracts 2 events', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events.length).toBe(2);
    });

    test('extracts event name', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[0].name).toMatch(/Dweller Thursday/);
    });

    test('extracts venue', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[0].venue_name).toBe('Paragon');
    });

    test('extracts venue address', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[0].venue_address).toMatch(/990 Broadway/);
    });

    test('extracts date', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[0].date_local).toBe('2026-02-19');
    });

    test('extracts start time', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[0].start_time_local).toMatch(/21:30/);
    });

    test('extracts end time', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[0].end_time_local).toMatch(/03:00/);
    });

    test('decodes source URL from tracking redirect', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[0].source_url).toBe('https://ra.co/events/2354432');
    });

    test('extracts price when present', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-20');
      expect(events[1].price_display).toBe('$15');
    });
  });

  describe('Template B: numbered <ol> with <br/> fields', () => {
    const html = `
      <h3>Fresh Indie Picks</h3>
      <ol>
        <li>"Mitski Residency" at The Shed<br/>545 W 30th St, Chelsea, Manhattan<br/>Tue Mar 3, 8:00 PM<br/>Price not listed<br/>Indie-pop artist in a six-night run.<br/>Details: https://www.theshed.org</li>
        <li>"Ten Dollar Tuesdays" at St. Marks Comedy Club<br/>12 St. Marks Place, East Village, Manhattan<br/>Tue Mar 3, 7:30 PM<br/>$10<br/>Early-week showcase of rising underground comedians.<br/>Details: https://www.stmarkscomedy.com</li>
      </ol>
      <p>Report generated by 200 agents</p>
    `;

    test('extracts 2 events', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events.length).toBe(2);
    });

    test('extracts quoted name', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events[0].name).toBe('Mitski Residency');
    });

    test('extracts venue from "at Venue" pattern', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events[0].venue_name).toBe('The Shed');
    });

    test('extracts address from <br/> line', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events[0].venue_address).toMatch(/545 W 30th St/);
    });

    test('extracts details URL', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events[0].source_url).toBe('https://www.theshed.org');
    });

    test('extracts price', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events[1].price_display).toBe('$10');
    });

    test('extracts description', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events[1].description_short).toMatch(/rising underground/);
    });

    test('extracts date and time', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-04');
      expect(events[0].date_local).toBe('2026-03-03');
      expect(events[0].start_time_local).toMatch(/20:00/);
    });
  });

  describe('Template C: paragraph-separated with <br/> fields', () => {
    const html = `
      <h3>Curated Indie in Manhattan</h3>
      <p style="color:rgb(55,65,81)">1) "The Legend of You" at Caveat<br/>21A Clinton St, Lower East Side<br/>Sat Mar 7, 1:30 PM<br/>$15–$20<br/>Comedy meets catharsis.<br/>Details: https://www.caveat.nyc/events</p>
      <p style="color:rgb(55,65,81)">2) "On the Watchlist" at Caveat<br/>21A Clinton St, Lower East Side<br/>Sat Mar 7, 4:00 PM<br/>$15–$20<br/>Live show that dismantles media narratives.<br/>Details: https://www.caveat.nyc/events</p>
      <p>Report generated by 200 agents</p>
    `;

    test('extracts 2 events', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-05');
      expect(events.length).toBe(2);
    });

    test('extracts name from numbered paragraph', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-05');
      expect(events[0].name).toBe('The Legend of You');
    });

    test('extracts venue', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-05');
      expect(events[0].venue_name).toBe('Caveat');
    });

    test('extracts address', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-05');
      expect(events[0].venue_address).toMatch(/21A Clinton/);
    });

    test('extracts price range', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-05');
      expect(events[0].price_display).toBe('$15–$20');
    });

    test('extracts URL', () => {
      const events = parseStructuredYutoriHtml(html, '2026-03-05');
      expect(events[0].source_url).toBe('https://www.caveat.nyc/events');
    });
  });

  describe('Template D: <p> name+desc + <ul> field labels', () => {
    const html = `
      <h3>Fresh underground bookings</h3>
      <p style="color:rgb(55,65,81)"><b style="font-weight:700">Brooklyn Experimental Electronic Music Showcase</b> — A curated night of experimental electronic sets. RSVP required. <span style="display:inline-block"><a href="https://scouts.yutori.com/api/view?url=https%3A%2F%2Fwww.wonderville.nyc%2Fevents%2Fbeem&amp;referrer=email&amp;scout_id=abc&amp;destination=source"><img src="fav"/><span>Event details</span></a></span></p>
      <ul>
        <li>Date &amp; time: Thursday, February 26, 2026 | 7:00 PM – 11:00 PM</li>
        <li>Venue: Wonderville, 1186 Broadway, Brooklyn, NY 11221</li>
        <li>Event type: Experimental electronic showcase</li>
        <li>Entry: RSVP required</li>
      </ul>
      <p style="color:rgb(55,65,81)"><b style="font-weight:700">Investigation | Freedom Attic</b> — Underground rock in a tight LES room. $12.44. <span style="display:inline-block"><a href="https://scouts.yutori.com/api/view?url=https%3A%2F%2Fberlin.nyc%2Ftm-event%2Finvestigation&amp;referrer=email&amp;scout_id=abc&amp;destination=source"><img src="fav"/><span>Event page</span></a></span></p>
      <ul>
        <li>Date &amp; time: Saturday, February 21, 2026 | 6:00 PM doors / 6:30 PM show</li>
        <li>Venue: Berlin, 25 Avenue A, New York, NY 10009</li>
        <li>Event type: Experimental rock / grunge</li>
        <li>Tickets: $12.44 (includes fees)</li>
      </ul>
      <p>Report generated by 102 agents</p>
    `;

    test('extracts 2 events', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events.length).toBe(2);
    });

    test('extracts name from bold tag', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[0].name).toBe('Brooklyn Experimental Electronic Music Showcase');
    });

    test('extracts venue from field label', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[0].venue_name).toBe('Wonderville');
    });

    test('extracts address from venue field', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[0].venue_address).toMatch(/1186 Broadway/);
    });

    test('extracts date from field label', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[0].date_local).toBe('2026-02-26');
    });

    test('extracts time from field label', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[0].start_time_local).toMatch(/19:00/);
    });

    test('decodes source URL', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[0].source_url).toBe('https://www.wonderville.nyc/events/beem');
    });

    test('extracts description', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[0].description_short).toMatch(/experimental electronic/);
    });

    test('extracts price from tickets field', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[1].price_display).toBe('$12.44');
    });

    test('extracts second event venue', () => {
      const events = parseStructuredYutoriHtml(html, '2026-02-21');
      expect(events[1].venue_name).toBe('Berlin');
    });
  });

  describe('edge cases', () => {
    test('returns empty array for non-event HTML', () => {
      const html = '<h3>AI News</h3><p>GPT-5 is out.</p><p>Report generated by 10 agents</p>';
      const events = parseStructuredYutoriHtml(html, '2026-03-06');
      expect(events.length).toBe(0);
    });

    test('handles HTML entities in names', () => {
      const html = `<ol><li>"Rock &amp; Roll Night" at Joe&#x27;s Pub<br/>425 Lafayette St<br/>Fri Mar 7, 9:00 PM<br/>$20<br/>Great show.</li></ol><p>Report generated by 10 agents</p>`;
      const events = parseStructuredYutoriHtml(html, '2026-03-07');
      expect(events[0].name).toBe('Rock & Roll Night');
      expect(events[0].venue_name).toBe("Joe's Pub");
    });

    test('skips TL;DR paragraphs', () => {
      const html = `
        <h3>Test</h3>
        <p>TL;DR: Five intimate picks across Brooklyn.</p>
        <p>1) "Show" at Venue<br/>123 Main St<br/>Fri Mar 7, 9 PM<br/>$10<br/>Good show.</p>
        <p>Report generated by 10 agents</p>
      `;
      const events = parseStructuredYutoriHtml(html, '2026-03-07');
      expect(events.length).toBe(1);
      expect(events[0].name).toBe('Show');
    });
  });
});
